package com.example.game.world

enum class TileType(
    val isSolid: Boolean = false,
    val isOneWay: Boolean = false,
    val isLadder: Boolean = false,
    val isHazard: Boolean = false,
    val isWater: Boolean = false,
    val isInteractive: Boolean = false
) {
    AIR,
    GRASS_TOP(isSolid = true),
    GRASS_LEFT(isSolid = true),
    GRASS_RIGHT(isSolid = true),
    DIRT(isSolid = true),
    STONE_BLOCK(isSolid = true),
    STONE_BRICK(isSolid = true),
    CAVE_ROCK(isSolid = true),
    CAVE_WALL(isSolid = false),
    WOOD_PLATFORM(isSolid = true, isOneWay = true),
    LADDER(isLadder = true),
    SPIKE_HAZARD(isHazard = true),
    WATER(isWater = true),
    TORCH_WALL(isInteractive = false),
    RUIN_PILLAR(isSolid = false),
    RUIN_STONE(isSolid = true),
    RUIN_CRUMBLE_BLOCK(isSolid = true),
    VILLAGE_COBBLE(isSolid = true),
    COBBLESTONE(isSolid = true),
    VILLAGE_WOOD_WALL(isSolid = false),
    WOOD_PLANK(isSolid = true),
    VILLAGE_ROOF(isSolid = true),
    ROOF_TILE(isSolid = true),
    VILLAGE_LANTERN(isSolid = false),
    SNOW_TOP(isSolid = true),
    ICE_BLOCK(isSolid = true),
    SHRINE_ALTAR(isSolid = true),
    SHRINE_RUNE_PILLAR(isSolid = false),
    CASTLE_WALL(isSolid = false),
    CASTLE_BANNER(isSolid = false),
    WATERFALL(isSolid = false),
    CHEST_OBJECT(isInteractive = true),
    CHECKPOINT_OBJECT(isInteractive = true),
    PORTAL_OBJECT(isInteractive = true)
}
